DROP TABLE IF EXISTS clothes;
DROP TABLE IF EXISTS customer;


--DROP SEQUENCE IF EXISTS groups_seq;
--DROP SEQUENCE IF EXISTS lesson_seq;
--
--CREATE SEQUENCE groups_seq START WITH 1;
--CREATE SEQUENCE lesson_seq START WITH 1;

CREATE TABLE customer
(
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  name       VARCHAR(100) NOT NULL,
  phone	     VARCHAR(100) NOT NULL
);
--UNIQUE
CREATE TABLE clothes
(
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  kind      VARCHAR(100) NOT NULL,
  price     INTEGER NOT NULL,
  cust_id INTEGER NOT NULL,
  CONSTRAINT fk FOREIGN KEY (cust_id) REFERENCES customer (id) ON DELETE CASCADE ON UPDATE CASCADE
);


--CREATE TABLE groups
--(
--  id         INTEGER PRIMARY KEY DEFAULT nextval('groups_seq'),
--  name       VARCHAR NOT NULL,
--  faculty	 VARCHAR NOT NULL
--);

--CREATE TABLE lesson
--(
--  id        INTEGER PRIMARY KEY DEFAULT nextval('lesson_seq'),
--  name      VARCHAR NOT NULL,
--  room      VARCHAR NOT NULL,
--  groups_id  INTEGER NOT NULL,
--  FOREIGN KEY (groups_id) REFERENCES groups (id) ON DELETE CASCADE ON UPDATE CASCADE
--);